server:
    port: 8088
    ssl:
        enabled: true
        key-store: classpath:config/ssltest.pkcs12
        key-store-password: 123456
        key-store-type: pkcs12
        keyAlias: ssltest
spring:
    application:
        name: simple
    datasource:
        hikari:
            maximum-pool-size: 4
        url: ${psql.url}
        username: ${psql.username}
        password: ${psql.password}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
    thymeleaf:
        cache: false
    ai:
        openai:
            api-key: ${apikey.openai}
