/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-01-31 08:13:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.testt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class JspTest2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"EUC-KR\">\r\n");
      out.write("  <title>Document</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"myPage.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"b.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"header\">vroom header</div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("      <div class=\"greenContainer\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <div class=\"name\">Jaden</div>\r\n");
      out.write("        </div>    \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"summaryContainer\">\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <div class=\"number\">354</div>\r\n");
      out.write("            <div>단골상점</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"number\">354</div>\r\n");
      out.write("            <div>상품후기</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"number\">354</div>\r\n");
      out.write("            <div>적립금(BLCT)</div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("      <div class=\"shippingStatusContainer\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("          주문 내역\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"status\">\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"text\">전체</div>\r\n");
      out.write("              <div class=\"green number\">6</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"text\">결제중</div>\r\n");
      out.write("              <div class=\"number\">0</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"text\">배송중</div>\r\n");
      out.write("              <div class=\"green number\">1</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"text\">구매확정</div>\r\n");
      out.write("              <div class=\"green number\">3</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>  \r\n");
      out.write("      <div style=\"width : 100%; height: 300px; background-color: blue; color: white; font-size: 20px;\"  >\r\n");
      out.write("        사진이랑 설명 가격 들어갈 거야 3개 + 더보기 버튼\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"shippingStatusContainer\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("          판매 내역\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"status\">\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"green number\">6</div>\r\n");
      out.write("              <div class=\"text\">장바구니</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"number\">0</div>\r\n");
      out.write("              <div class=\"text\">결제완료</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"green number\">1</div>\r\n");
      out.write("              <div class=\"text\">배송중</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <div class=\"green number\">3</div>\r\n");
      out.write("              <div class=\"text\">구매확정</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>     \r\n");
      out.write("        </div>\r\n");
      out.write("      </div> \r\n");
      out.write("      <div style=\"width : 100%; height: 300px; background-color: blue; color: white; font-size: 20px;\"  >\r\n");
      out.write("        사진이랑 설명 가격 들어갈 거야 3개 + 더보기 버튼\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"listContainer\">\r\n");
      out.write("        <a href=\"#\" class=\"item\">\r\n");
      out.write("            <div class=\"icon\">ii</div>\r\n");
      out.write("            <div class=\"text\">판매목록<span class=\"circle\"></span></div>\r\n");
      out.write("            <div class=\"right\"> > </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"item\">\r\n");
      out.write("            <div class=\"icon\">ii</div>\r\n");
      out.write("            <div class=\"text\">구매목록</div>\r\n");
      out.write("            <div class=\"right\"> > </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"item\">\r\n");
      out.write("            <div class=\"icon\">ii</div>\r\n");
      out.write("            <div class=\"text\">단골상점</div>\r\n");
      out.write("            <div class=\"right\"> > </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"item\">\r\n");
      out.write("            <div class=\"icon\">ii</div>\r\n");
      out.write("            <div class=\"text\">찜한상품</div>\r\n");
      out.write("            <div class=\"right\"> > </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
